name: CI
on:
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"

jobs:
  test-alpine:
    runs-on: tox-alpine-pod
    strategy:
      matrix:
        cc: [gcc, clang]
    steps:
    - run: |
        sudo apk add --no-cache \
          meson \
          build-base \
          gcc \
          clang \
        && :
    - uses: actions/checkout@v4
    - name: configure
      run: |
        CC=${{ matrix.cc }} meson setup build \
          -Dwerror=true \
          -Dtest=true \
        && :
    - name: build
      run: ninja -C build all
    - name: test
      run: ninja -C build test
